### ISSUE TITLE
No command to exit

### ISSUE THREAD

**Issue by FromSi** [nandydark/grim#1]
Plz, add command for exit/quit.

![image](https://user-images.githubusercontent.com/22871855/102013689-f3790b00-3d7b-11eb-8123-c9d7c9b77019.png)

**Comment by FromSi** [comment]
I like that I can exit the app after entering the URL.
Don't you think that this menu is useless and everything can fit at the moment of entering the URL? (part 1)
![image](https://user-images.githubusercontent.com/22871855/102014026-0391ea00-3d7e-11eb-8791-f631c5820b76.png)

**Comment by nandydark** [comment]
Yeah well i haven't thought about it yet but yeah it's a good idea
